environment:
  SAB_NEWSSERVER_HOST:
    secure: 6SvOPWr5ypJeoumXJAZh90DLpk4C/5UAvzwyX7OOUr4=
  SAB_NEWSSERVER_USER:
    secure: Ty3ZG8T5vnacqIFPj5j5hg==
  SAB_NEWSSERVER_PASSWORD:
    secure: bO3XHtWTleVF9AqRV/V/nA==

install:
  - pip install --upgrade -r tests/requirements.txt
  - pip install pypiwin32 subprocessww

build_script:
  - python ./tests/test_functional.py
